package br.ce.gov.fortaleza.acao;

public class AcaoGenXSD extends javax.swing.JFrame {

    /**
     * Creates new form ContactEditor
     */
    public AcaoGenXSD() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPCorpoXml = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jCBTipoCampo = new javax.swing.JComboBox();
        jPTextArea = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton17 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jPTexto = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton18 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jPInteiro = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton19 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPNumerico = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jButton20 = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jPTextoFormatado = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jButton25 = new javax.swing.JButton();
        jTextField27 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jCBTipoCampo1 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jPRadioButton = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jCheckBox9 = new javax.swing.JCheckBox();
        jButton22 = new javax.swing.JButton();
        jTextField21 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jCBTipoCampo2 = new javax.swing.JComboBox();
        jTextField26 = new javax.swing.JTextField();
        jPSelecao = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jCBTipoCampo3 = new javax.swing.JComboBox();
        jButton27 = new javax.swing.JButton();
        jPCheckBox = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jCheckBox11 = new javax.swing.JCheckBox();
        jButton24 = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jCBTipoCampo4 = new javax.swing.JComboBox();
        jTextField34 = new javax.swing.JTextField();
        jPComplexo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jCheckBox10 = new javax.swing.JCheckBox();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList();
        jButton23 = new javax.swing.JButton();
        jTextField23 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-mail Contacts");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                teste(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabeçalho\n\n"));

        jLabel1.setText("targetNamespace");

        jTextField1.setText("http://schemas.fortaleza.ce.gov.br/acao/habitafor-atualizacaocadastral-cas.xsd");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(161, 227, 231));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerador de XSD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButton7.setText("Novo");

        jButton10.setText("Sobre");

        jButton12.setText("Close");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton12)
                .addContainerGap(1200, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton7)
                    .add(jButton10)
                    .add(jButton12))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPCorpoXml.setBorder(javax.swing.BorderFactory.createTitledBorder("Corpo XML"));

        jLabel9.setText("Tipo");

        jButton11.setText("Novo Campo");

        jCBTipoCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha o Campo", "Texto Area", "Texto", "Texto Formatado", "Inteiro", "Numerico", "Seleção", "Radio button", "Check box", "Complexo", " " }));
        jCBTipoCampo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clickCampo(evt);
            }
        });
        jCBTipoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoCampoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPCorpoXmlLayout = new org.jdesktop.layout.GroupLayout(jPCorpoXml);
        jPCorpoXml.setLayout(jPCorpoXmlLayout);
        jPCorpoXmlLayout.setHorizontalGroup(
            jPCorpoXmlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPCorpoXmlLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jButton11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCBTipoCampo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(967, Short.MAX_VALUE))
        );
        jPCorpoXmlLayout.setVerticalGroup(
            jPCorpoXmlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPCorpoXmlLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPCorpoXmlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton11)
                    .add(jLabel9)
                    .add(jCBTipoCampo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Texto Area"));

        jLabel11.setText("Identificador");

        jCheckBox4.setText("Obrigatório");

        jButton17.setText("Add Campo");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jTextField11.setText("Digite aqui o titulo do campo ");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel12.setText("Titulo ");

        jTextField32.setText("Digite aqui o identificador do campo ");
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPTextAreaLayout = new org.jdesktop.layout.GroupLayout(jPTextArea);
        jPTextArea.setLayout(jPTextAreaLayout);
        jPTextAreaLayout.setHorizontalGroup(
            jPTextAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPTextAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel12)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPTextAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPTextAreaLayout.createSequentialGroup()
                        .add(jCheckBox4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton17))
                    .add(jTextField11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .add(jTextField32, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPTextAreaLayout.setVerticalGroup(
            jPTextAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPTextAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jTextField32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPTextAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPTextAreaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton17))
                .add(18, 18, 18))
        );

        jPTexto.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Texto "));

        jLabel13.setText("Identificador");

        jCheckBox5.setText("Obrigatório");

        jButton18.setText("Add Campo");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jTextField13.setText("Digite aqui o titulo do campo ");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jLabel14.setText("Titulo ");

        jTextField31.setText("Digite aqui o identificador do campo ");
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPTextoLayout = new org.jdesktop.layout.GroupLayout(jPTexto);
        jPTexto.setLayout(jPTextoLayout);
        jPTextoLayout.setHorizontalGroup(
            jPTextoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPTextoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPTextoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(jLabel13))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPTextoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPTextoLayout.createSequentialGroup()
                        .add(jCheckBox5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton18))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField13)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField31, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPTextoLayout.setVerticalGroup(
            jPTextoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPTextoLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPTextoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jTextField31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPTextoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(jTextField13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPTextoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton18))
                .add(18, 18, 18))
        );

        jPInteiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Inteiro"));

        jLabel15.setText("Identificador");

        jCheckBox6.setText("Obrigatório");

        jButton19.setText("Add Campo");

        jTextField15.setText("Digite aqui o titulo do campo ");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel16.setText("Titulo ");

        jTextField16.setText("Digite aqui o identificador do campo ");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPInteiroLayout = new org.jdesktop.layout.GroupLayout(jPInteiro);
        jPInteiro.setLayout(jPInteiroLayout);
        jPInteiroLayout.setHorizontalGroup(
            jPInteiroLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPInteiroLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPInteiroLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel16)
                    .add(jLabel15))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPInteiroLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPInteiroLayout.createSequentialGroup()
                        .add(jCheckBox6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton19))
                    .add(jTextField15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .add(jTextField16, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPInteiroLayout.setVerticalGroup(
            jPInteiroLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPInteiroLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPInteiroLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(jTextField16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPInteiroLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(jTextField15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPInteiroLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .add(jButton19))
                .addContainerGap())
        );

        jPNumerico.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Numerico"));

        jLabel17.setText("Identificador");

        jCheckBox7.setText("Obrigatório");

        jButton20.setText("Add Campo");

        jTextField17.setText("Digite aqui o titulo do campo ");
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        jLabel18.setText("Titulo ");

        jLabel30.setText("Qtd Casa decimal");

        jTextField28.setText("Digite a quantidade de casas decimais");
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });

        jTextField29.setText("Digite aqui identificador do campo ");
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPNumericoLayout = new org.jdesktop.layout.GroupLayout(jPNumerico);
        jPNumerico.setLayout(jPNumericoLayout);
        jPNumericoLayout.setHorizontalGroup(
            jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPNumericoLayout.createSequentialGroup()
                .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPNumericoLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel18)
                            .add(jLabel17)
                            .add(jLabel30))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPNumericoLayout.createSequentialGroup()
                                .add(jTextField28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 833, Short.MAX_VALUE)
                                .add(jButton20))
                            .add(jTextField17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                            .add(jTextField29, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)))
                    .add(jPNumericoLayout.createSequentialGroup()
                        .add(102, 102, 102)
                        .add(jCheckBox7)))
                .addContainerGap())
        );
        jPNumericoLayout.setVerticalGroup(
            jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPNumericoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(jTextField29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(jTextField17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPNumericoLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel30)
                            .add(jTextField28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPNumericoLayout.createSequentialGroup()
                        .add(jPNumericoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPNumericoLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton20))
                            .add(jPNumericoLayout.createSequentialGroup()
                                .add(52, 52, 52)
                                .add(jCheckBox7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(38, 38, 38))))
        );

        jPTextoFormatado.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Texto  Formatado"));

        jLabel27.setText("Identificador");

        jCheckBox12.setText("Obrigatório");

        jButton25.setText("Add Campo");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jTextField27.setText("Digite aqui o titulo do campo ");
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });

        jLabel28.setText("Titulo ");

        jCBTipoCampo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha o tipo de mascara", "Fone - (xx)xxxx-xxxx", "CPF - xxx.xxx.xxx-xx", "Cep - xxxxx-xx", " " }));
        jCBTipoCampo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoCampo1clickCampo(evt);
            }
        });
        jCBTipoCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoCampo1ActionPerformed(evt);
            }
        });

        jLabel29.setText("Mascara");

        jTextField30.setText("Digite aqui o identificador do campo ");
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPTextoFormatadoLayout = new org.jdesktop.layout.GroupLayout(jPTextoFormatado);
        jPTextoFormatado.setLayout(jPTextoFormatadoLayout);
        jPTextoFormatadoLayout.setHorizontalGroup(
            jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPTextoFormatadoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel28)
                    .add(jLabel27)
                    .add(jLabel29))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField27, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .add(jTextField30, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .add(jPTextoFormatadoLayout.createSequentialGroup()
                        .add(jCheckBox12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1056, Short.MAX_VALUE)
                        .add(jButton25))
                    .add(jCBTipoCampo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPTextoFormatadoLayout.setVerticalGroup(
            jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPTextoFormatadoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel27)
                    .add(jTextField30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel28)
                    .add(jTextField27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel29)
                    .add(jCBTipoCampo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPTextoFormatadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton25)
                    .add(jCheckBox12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
        );

        jPRadioButton.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Radio Button"));

        jLabel21.setText("Identificador");

        jTextField20.setText("Digite aqui o identeficador do campo ");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Obrigatório");

        jButton22.setText("Add Campo");

        jTextField21.setText("Digite aqui o titulo do campo ");
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jLabel22.setText("Titulo ");

        jButton26.setText("Add ");

        jCBTipoCampo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha o Tipo", "String", "Inteiro", "Boolean" }));
        jCBTipoCampo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoCampo2clickCampo(evt);
            }
        });
        jCBTipoCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoCampo2ActionPerformed(evt);
            }
        });

        jTextField26.setText("Digite aqui o titulo do campo ");
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPRadioButtonLayout = new org.jdesktop.layout.GroupLayout(jPRadioButton);
        jPRadioButton.setLayout(jPRadioButtonLayout);
        jPRadioButtonLayout.setHorizontalGroup(
            jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPRadioButtonLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel21)
                    .add(jPRadioButtonLayout.createSequentialGroup()
                        .add(jLabel22)
                        .add(59, 59, 59)
                        .add(jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPRadioButtonLayout.createSequentialGroup()
                                .add(jButton26)
                                .add(28, 28, 28)
                                .add(jCBTipoCampo2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField21, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField26, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPRadioButtonLayout.createSequentialGroup()
                                .add(jCheckBox9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1053, Short.MAX_VALUE)
                                .add(jButton22)))))
                .addContainerGap())
        );
        jPRadioButtonLayout.setVerticalGroup(
            jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPRadioButtonLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel21)
                    .add(jTextField20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton26)
                    .add(jCBTipoCampo2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jTextField26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPRadioButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton22))
                .addContainerGap())
        );

        jPSelecao.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Seleçao"));

        jLabel19.setText("Identificador");

        jCheckBox8.setText("Obrigatório");

        jLabel20.setText("Titulo ");

        jTextField18.setText("Digite aqui o identificador do campo ");
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jTextField19.setText("Digite aqui o titulo do campo ");
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jTextField33.setText("Digite aqui o titulo do campo ");
        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });

        jButton21.setText("Add Campo");

        jCBTipoCampo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha o Tipo", "String", "Inteiro", "Boolean", " ", " ", " " }));
        jCBTipoCampo3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoCampo3clickCampo(evt);
            }
        });
        jCBTipoCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoCampo3ActionPerformed(evt);
            }
        });

        jButton27.setText("Add ");

        org.jdesktop.layout.GroupLayout jPSelecaoLayout = new org.jdesktop.layout.GroupLayout(jPSelecao);
        jPSelecao.setLayout(jPSelecaoLayout);
        jPSelecaoLayout.setHorizontalGroup(
            jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPSelecaoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel19)
                    .add(jLabel20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPSelecaoLayout.createSequentialGroup()
                        .add(jButton27)
                        .add(30, 30, 30)
                        .add(jCBTipoCampo3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPSelecaoLayout.createSequentialGroup()
                        .add(jCheckBox8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1056, Short.MAX_VALUE)
                        .add(jButton21))
                    .add(jTextField19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField33, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .add(jTextField18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPSelecaoLayout.setVerticalGroup(
            jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPSelecaoLayout.createSequentialGroup()
                .add(jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel19)
                    .add(jTextField18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(23, 23, 23)
                .add(jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel20)
                    .add(jTextField19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton27)
                    .add(jCBTipoCampo3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPSelecaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPSelecaoLayout.createSequentialGroup()
                        .add(jButton21)
                        .addContainerGap())
                    .add(jCheckBox8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
        );

        jPCheckBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Check Box"));

        jLabel25.setText("Identificador");

        jTextField24.setText("Digite aqui o indentificador do campo ");
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("Obrigatório");

        jButton24.setText("Add Campo");

        jTextField25.setText("Digite aqui o titulo do campo ");
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });

        jLabel26.setText("Titulo ");

        jButton28.setText("Add ");

        jCBTipoCampo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha o Tipo", "String", "Inteiro", "Boolean" }));
        jCBTipoCampo4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoCampo4clickCampo(evt);
            }
        });
        jCBTipoCampo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoCampo4ActionPerformed(evt);
            }
        });

        jTextField34.setText("Digite aqui o titulo do campo ");
        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPCheckBoxLayout = new org.jdesktop.layout.GroupLayout(jPCheckBox);
        jPCheckBox.setLayout(jPCheckBoxLayout);
        jPCheckBoxLayout.setHorizontalGroup(
            jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPCheckBoxLayout.createSequentialGroup()
                .add(jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPCheckBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel26)
                            .add(jLabel25))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField25, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField24, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                            .add(jPCheckBoxLayout.createSequentialGroup()
                                .add(jButton28)
                                .add(33, 33, 33)
                                .add(jCBTipoCampo4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPCheckBoxLayout.createSequentialGroup()
                        .add(104, 104, 104)
                        .add(jCheckBox11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1064, Short.MAX_VALUE)
                        .add(jButton24))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPCheckBoxLayout.createSequentialGroup()
                        .add(115, 115, 115)
                        .add(jTextField34, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPCheckBoxLayout.setVerticalGroup(
            jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPCheckBoxLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel25)
                    .add(jTextField24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel26)
                    .add(jTextField25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton28)
                    .add(jCBTipoCampo4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(jPCheckBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton24)))
        );

        jPComplexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Complexo"));

        jLabel23.setText("Identificador");

        jTextField22.setText("Digite aqui o nome do campo\n");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("Obrigatório");

        jList9.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jList9);

        jButton23.setText("Add Campo");

        jTextField23.setText("Digite aqui o nome do campo\n");
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });

        jLabel24.setText("Titulo ");

        org.jdesktop.layout.GroupLayout jPComplexoLayout = new org.jdesktop.layout.GroupLayout(jPComplexo);
        jPComplexo.setLayout(jPComplexoLayout);
        jPComplexoLayout.setHorizontalGroup(
            jPComplexoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPComplexoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPComplexoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel24)
                    .add(jLabel23))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPComplexoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPComplexoLayout.createSequentialGroup()
                        .add(227, 227, 227)
                        .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jTextField23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField22, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE)
                    .add(jPComplexoLayout.createSequentialGroup()
                        .add(jCheckBox10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1056, Short.MAX_VALUE)
                        .add(jButton23)))
                .addContainerGap())
        );
        jPComplexoLayout.setVerticalGroup(
            jPComplexoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPComplexoLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPComplexoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23)
                    .add(jTextField22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPComplexoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel24)
                    .add(jTextField23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPComplexoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPComplexoLayout.createSequentialGroup()
                        .add(jCheckBox10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(60, 60, 60)
                        .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButton23))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));

        jLabel3.setText("Nome do Formulario");

        jLabel4.setText("Classificação");

        jTextField6.setText("Digite aqui a classificaão do formulario");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setText("Digite aqui o indice");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Indice");

        jLabel8.setText("Titulo");

        jTextField8.setText("Digite aqui o titulo");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField4.setText("Digite aqui o nome do formulario");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel8))
                        .add(66, 66, 66)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
                            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField8)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)))))
                .add(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(7, 7, 7)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleName("Nome_Formulario");

        jPanel6.setBackground(new java.awt.Color(167, 207, 210));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButton8.setText("Salvar");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton8)
                .addContainerGap(1311, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jButton8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPTextoFormatado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jPTexto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPInteiro, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPNumerico, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jPSelecao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jPRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPCheckBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jPComplexo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPTextArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPCorpoXml, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPCorpoXml, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPTextArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPTexto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPTextoFormatado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPInteiro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPNumerico, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPSelecao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPCheckBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPComplexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("name  ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void close(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close
        System.exit(0);
    }//GEN-LAST:event_close

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void teste(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_teste
        // TODO add your handling code here:
        jPTextArea.setVisible(false);
        jPTexto.setVisible(false);
        jPTextoFormatado.setVisible(false);
        jPInteiro.setVisible(false);
        jPNumerico.setVisible(false);
        jPSelecao.setVisible(false);
        jPRadioButton.setVisible(false);
        jPCheckBox.setVisible(false);
        jPComplexo.setVisible(false);
    }//GEN-LAST:event_teste

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jCBTipoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampoActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void clickCampo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clickCampo
        // TODO add your handling code here:

        int itemCampo;

        itemCampo = jCBTipoCampo.getSelectedIndex();
       // index.setText(Integer.toString(itemCampo));


       switch (itemCampo) {
            case 1:
                jPTextArea.setVisible(true);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(false);
                break;
            case 2:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(true);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(false);
                break;
            case 3:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(true);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(false);
                break;
            case 4:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(true);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(false);
                break;
            case 5:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(true);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(false);
                break;
            case 6:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(true);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(false);
                break;
            case 7:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(true);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(false);
                break;
            case 8:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(true);
                jPComplexo.setVisible(false);
                break;
            case 9:

                jPTextArea.setVisible(false);
                jPTexto.setVisible(false);
                jPTextoFormatado.setVisible(false);
                jPInteiro.setVisible(false);
                jPNumerico.setVisible(false);
                jPSelecao.setVisible(false);
                jPRadioButton.setVisible(false);
                jPCheckBox.setVisible(false);
                jPComplexo.setVisible(true);
                break;
            default:
                System.out.println("Este não é um dia válido!");
        }
    }//GEN-LAST:event_clickCampo

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jCBTipoCampo1clickCampo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoCampo1clickCampo
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo1clickCampo

    private void jCBTipoCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo1ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField20ActionPerformed

    private void jCBTipoCampo2clickCampo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoCampo2clickCampo
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo2clickCampo

    private void jCBTipoCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo2ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jCBTipoCampo3clickCampo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoCampo3clickCampo
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo3clickCampo

    private void jCBTipoCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoCampo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo3ActionPerformed

    private void jCBTipoCampo4clickCampo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoCampo4clickCampo
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo4clickCampo

    private void jCBTipoCampo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoCampo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoCampo4ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AcaoGenXSD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jCBTipoCampo;
    private javax.swing.JComboBox jCBTipoCampo1;
    private javax.swing.JComboBox jCBTipoCampo2;
    private javax.swing.JComboBox jCBTipoCampo3;
    private javax.swing.JComboBox jCBTipoCampo4;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList9;
    private javax.swing.JPanel jPCheckBox;
    private javax.swing.JPanel jPComplexo;
    private javax.swing.JPanel jPCorpoXml;
    private javax.swing.JPanel jPInteiro;
    private javax.swing.JPanel jPNumerico;
    private javax.swing.JPanel jPRadioButton;
    private javax.swing.JPanel jPSelecao;
    private javax.swing.JPanel jPTextArea;
    private javax.swing.JPanel jPTexto;
    private javax.swing.JPanel jPTextoFormatado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
